### ISSUE TITLE
rethink error handling.

### ISSUE THREAD

**Issue by fakeshadow** [benwis/tower-governor#16]
The current way of handling error is both aggressive and bloated at the same time.

Imagine two use cases of this crate:

- in some generic tower service tree that is not `axum`
```rust
use http::{Request, Response};
use tower::{ServiceBuilder, ServiceExt};
use tower_governor::{governor::GovernorConfigBuilder, GovernorLayer};

#[derive(Debug, thiserror::Error)]
#[error("MyError")]
struct MyError;

#[tokio::main]
async fn main() {
    let governor_conf = Box::new(
        GovernorConfigBuilder::default()
            .per_second(60)
            .burst_size(10)
            .finish()
            .unwrap(),
    );

    // MyError type is lost because of governor layer and dynamic type casting is forced.
    let _e = ServiceBuilder::new()
        .layer(GovernorLayer {
            config: Box::leak(governor_conf),
        })
        .service_fn(|_: Request<()>| async { Err::<Response<String>, _>(MyError) })
        .oneshot(Request::default())
        .await
        .unwrap_err();
}
```

- in `axum` the caller is forced to write `HandleErrorLayer`.
```rust
Router::new() .route(..).layer(GovernorLayer { .. }) // ideally this is what I want to write for a middleware
```

In other word the middleware force user to do runtime type casting no matter where it's used.

To make the API simpler I would suggest make use of the `Response<Body>` type for everything the governor would produce and just pass through the inner Layer's `Service::Error` type.  For example:
```rust
impl<K, S, ReqBody, ResBody> Service<Request<ReqBody>>
    for Governor<K, StateInformationMiddleware, S>
where
    K: KeyExtractor,
    S: Service<Request<ReqBody>, Response = Response<ResBody>>,
    // convert error string to ResBody. this works because axum has impl From<String> for axum::body::Body
    ResBody: From<String>, 
{
    type Response = S::Response;
    // forward error type for S 
    type Error = S::Error; 
    type Future = ResponseFuture<S::Future>;
```

This change would resolve the case 2 issue completely and no more `HandleErrorLayer` is needed for `axum`. For case 1 it keeps it's type error and need an extra `impl From<String>` for it's body type. Which is much easier because convert a String to http body is trivial in most case.

I can make an PR for this change if it's desired.

**Comment by benwis** [comment]
Thanks for posting this. I agree the error handling is suboptimal, it was mostly copied from a different crate. I'd be happy to have a PR implementing those changes

**Comment by fakeshadow** [comment]
A PR has been made to implement suggested change mentioned in this issue. That said there maybe people still want to opt-in to handle typed error in place and generate http response on demand. Please let me know if that's the case and I can make future PR to add opt-in handler for it.

**Comment by benwis** [comment]
> A PR has been made to implement suggested change mentioned in this issue. That said there maybe people still want to opt-in to handle typed error in place and generate http response on demand. Please let me know if that's the case and I can make future PR to add opt-in handler for it.

Happy to merge the PR, I'm hesitant to break existing deploys of tower-governor with an update. If you can add an opt-in for the previous version, I should be able to push a release

**Comment by fakeshadow** [comment]
> > A PR has been made to implement suggested change mentioned in this issue. That said there maybe people still want to opt-in to handle typed error in place and generate http response on demand. Please let me know if that's the case and I can make future PR to add opt-in handler for it.
> 
> Happy to merge the PR, I'm hesitant to break existing deploys of tower-governor with an update. If you can add an opt-in for the previous version, I'll update the examples, and I should be able to push a release

Ok it's no problem. What style of API would you prefer for typed error handling? Personally I believe the most simple way it to add a callback to governor. For example:
```rust
GovernorConfigBuilder::default().error_handler(|e: GovernorError| {
    e.display_error() // this would be what the new default be and user can offer their own logic to produce a Response
})
```

Let me know what you think of the API.

**Comment by benwis** [comment]
Yeah, callback api is a solid choice for this use case

**Comment by fakeshadow** [comment]
ok. I'll follow up on the PR and add an error handler.

**Comment by fakeshadow** [comment]
> Thanks @fakeshadow for the contributions! I have released a new version with the changes, let me know if anything else comes up

Great I tried 0.3 on axum 0.7 and my personal web framework and it works fine. For any `tower` and `http` crates compat web solution it should pretty easy to hook into. I have not tested `tonic` though as obviously it still stuck with axum 0.6 and hyper 0.14

**Comment by benwis** [comment]
Yeah, that's good to hear. Tonic is definitely an odd case, we don't use it over here. I'll probably ask them to check it out if they need it
