### ISSUE TITLE
Remove `axum` feature in the documentation

### ISSUE THREAD

**Issue by Dawsoncodes** [benwis/tower-governor#20]
I have tried to install the package with the `axum` feature but I get this error from rust analyzer

Cargo.toml
```toml
tower_governor = { version = "0.3.0", features = ["tracing", "axum"] }
```

```bash
the package `server` depends on `tower_governor`, with features: `axum` but `tower_governor` does not have these features.
 It has a required dependency with that name, but only optional dependencies can be used as features.
```

The documentation is misleading because the packages doesn't have feature `axum` but it says it does.

**Comment by benwis** [comment]
Could you try installing the git version? There was a PR that I think might fix this that I haven't made a new release for

**Comment by benwis** [comment]
I'm not quite sure, if I clone the reop, go to examples, and run `cargo run --bin=basic`
 I get the expected output

**Comment by Dawsoncodes** [comment]
There was an issue on my end and I fixed it, thank you very much for your time.

**Comment by benwis** [comment]
Thank you! I'll push out a new release so that others won't experience it
