### ISSUE TITLE
Relax From<String> constraint on the Response?

### ISSUE THREAD

**Issue by itsbalamurali** [benwis/tower-governor#21]
Hi Ben,

Thanks for the amazing library,

Is it possible to relax the From<String> constraint on the Response for the error_handler ?

I am having a custom json body that I am constructing from a Error response type with into_response implementation that make it hard to use error_handler with custom response types.

**Comment by benwis** [comment]
I'm not really sure, if you'd like to try it I suspect it could work.

**Comment by GenericNerd** [comment]
Big +1 for this

**Comment by GenericNerd** [comment]
@itsbalamurali I've created a PR that resolves this issue by using a `axum::body::Body` type instead. Hopefully the PR is merged in :)

**Comment by benwis** [comment]
Happy to merge, thanks @GenericNerd. Do you want to try it @itsbalamurali? I'll test it out today and put out a new release if so

**Comment by itsbalamurali** [comment]
Thanks @GenericNerd @benwis I have tried it and it works as expected.

**Comment by benwis** [comment]
> Just want to say `cargo build --no-default-features` does not build anymore with this change. The point of using String is to make `axum` optional because this crate is named as `tower-governor`. Imagine people not using `axum`. Must be shocking right?
> 
> If you really want to force `axum` on everyone please consider change the crate name to `axum-governor`.

For clarity's sake, I don't want to force Axum on everyone, and should have considered the impact it would have on non Axum users. I think there's some room here to either move more things behind the axum feature flag or perhaps move to the more generic Body type used by hyper? Or maybe both?

Are you using hyper?

**Comment by GenericNerd** [comment]
> Just want to say `cargo build --no-default-features` does not build anymore with this change. The point of using String is to make `axum` optional because this crate is named as `tower-governor`. Imagine people not using `axum`. Must be shocking right?
> 
> If you really want to force `axum` on everyone please consider change the crate name to `axum-governor`.

I didn't even consider that! I wonder if the best thing is to allow a more generic type for the constraint that allows both people using axum and those that don't to still use tower-governor. Not entirely sure how that would be approached though.
