### ISSUE TITLE
Cannot create a function with `RateLimitingMiddleware`

### ISSUE THREAD

**Issue by woile** [benwis/tower-governor#23]
Hi, I'm trying to create a function that returns a `Box<GovernorConfig<PeerIpKeyExtractor, StateInformationMiddleware>>` but it seems that `GovernorConfig` in the root crate is private, and `StateInformationMiddleware` is also private.

In my axum project I have a `main` function that joins all the routes from different modules. I want to configure only a small set of routes with rate limiting, so I want to be able to create the rate limiting on demand.
Could those structs be made public?
Thanks

**Comment by GenericNerd** [comment]
Hey! I had the exact same intent as you, but there is now an alternate solution that I've used and it seems to work great.

The `.error_handler()` function from the GovernorConfigBuilder allows you to write a closure that you can make into an axum Response type.

**Comment by benwis** [comment]
Thanks! @GenericNerd is right, the goal with that function is to allow that. Let me know if that won't work for you and I can explore workarounds
