### ISSUE TITLE
Use `Arc` + `Weak` to improve use in frameworks and libraries

### ISSUE THREAD

**Issue by dpc** [benwis/tower-governor#25]
Thanks for this crate.

I've noticed it leaks a thread and a static reference, and I wonder if it would be better to `Arc` the `governor_conf`, spawn a thread with `Weak` of that `Arc`, so it can automatically quit when it is no longer needed (can't upgrade), and not require leaking anything anywhere. Sure most applications where axum is employed are just servers that start once, but I do write a lot of tooling, test-suites, etc. and shortcuts like this are common papercuts. I don't really see any downsides - derefering `Arc` is not slower than dereferencing `&'static T`

Also in my code I'll put the whole thread spawning into some `trait GovernorExt { fn spawn_background_thread() }` just to get it out of the way of the main function, and I wonder if `tower-governor` could just come with something like that - would make things just a bit shorter and cleaner.

Anyway, thanks again.

**Comment by benwis** [comment]
Thanks for looking into it. I don't see a problem with that. feel free to do it and put in a PR.

**Comment by benwis** [comment]
Thanks again for fixing this!
