### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by matteopolak** [benwis/tower-governor#32]
Hey, thanks for making this!

I'm not seeing a license, is it MIT/Apache2?

Edit: Found it in the `Cargo.toml` but it'd be great if you could create `LICENSE-MIT` and `LICENSE-APACHE` files in the root with a mention of it in the README for others with the same question :)

**Comment by benwis** [comment]
It is! It's listed in Cargo.toml but I didn't have a license file. Thanks for pointing this out!
